version: "1"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/node-app
      - /node-app/node_modules
    command: npm run dev
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "8081:8081"
    environment:
      MONGO_INITDB_ROOT_USERNAME: fundo
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-volume:/data/db

  redis: 
    image: redis
    
volumes:
  mongo-volume:
