version: "1"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/node-app
      - /node-app/node_modules
    command: npm run dev
    environment:
      - MONGO_USERNAME=fundo
      - MONG_PASSWORD=password
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "8081:8081"
    volumes:
      - db-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: fundo
      MONGO_INITDB_ROOT_PASSWORD: password

  redis:
    image: redis

volumes:
  db-volume:
